language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; pkg"build SymmetricTensors"; pkg"add Test"'
  - julia --code-coverage test/runtests.jl 
after_success:
  - julia -e 'import SymmetricTensors; using Pkg; pkg"add Coverage"; using Coverage; Coveralls.submit(process_folder())'
